# -*- coding: utf-8 -*-
"""scvi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-uA2lzAHA_gdniF8YLvdsKzUQ9uNNDZh
"""

!pip install --quiet scvi-colab
from scvi_colab import install

install()

# Commented out IPython magic to ensure Python compatibility.
import scanpy as sc
import scvi

sc.set_figure_params(figsize=(4, 4))

# for white background of figures (only for docs rendering)
# %config InlineBackend.print_figure_kwargs={'facecolor' : "w"}
# %config InlineBackend.figure_format='retina'

adata = scvi.data.heart_cell_atlas_subsampled()

sc.pp.filter_genes(adata, min_counts=3)

adata.layers["counts"] = adata.X.copy()  # preserve counts
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)
adata.raw = adata  # freeze the state in `.raw`

sc.pp.highly_variable_genes(
    adata,
    n_top_genes=1200,
    subset=True,
    layer="counts",
    flavor="seurat_v3",
    batch_key="cell_source",
)

model

model = scvi.model.SCVI(adata)

model.train()

model.save("heart_cell_model/")

model = scvi.model.SCVI.load("heart_cell_model", adata=adata)

latent = model.get_latent_representation()

adata.obsm["X_scVI"] = latent

adata_subset = adata[adata.obs.cell_type == "Fibroblast"]
latent_subset = model.get_latent_representation(adata_subset)

denoised = model.get_normalized_expression(adata_subset, library_size=1e4)
denoised.iloc[:5, :5]

adata.layers["scvi_normalized"] = model.get_normalized_expression(library_size=10e4)